### ISSUE TITLE
Health List 

### ISSUE THREAD

**Issue by sreerudra** [eVerveCorp/MyDailyBeat-iOS#29]
Please provide us with the list of Health care companies you need the App to display.

**Comment by waterloo72** [comment]
Hey guys,
We need to talk through this one because it was meant to be a place where
members could add the link to their doctor's office - health link. More and
more primary care providers offer this online service for patients to view
their lab results, schedule appointments, reorder prescriptions, etc.

In addition we would provide resources i.e., links to order prescriptions,
medical devices, and health and well-being books.

This is what we had spoken about before. Based on this, please confirm what
you will need or how we can make this page work. Thank you, Lisa

**Comment by waterloo72** [comment]
Thanks Lisa. Can you write up 3-4 paragraphs with some examples?

Thanks
Sastry

**Comment by waterloo72** [comment]
3 to 4 paragraphs of what? We spoke about these screens many times you took
notes and wrote up the functional requirements. Please let me know what is
not clear. The reason why I wanted to meet this weekend is to review all
the functionality because some of it seems to not be understood. I also
think we may need to trim it down so we can get the beta finished.
